const app = document.getElementById('start')
app.style.opacity = 0
let universe
let itemTrade

let start ={
//------------------------------------------------------------------------------
      soManyProblemWithSetTimeout: '',                                          //конфликт со сборщиком мусора и таймаутом
      bufer: null,                                                              //костыль невежества :(
//------------------------------------------------------------------------------
      removeDOM(all, ...args){                                                  //удаляет внутрянку у id элемента
            for(arg in args){
                  let doc = document.getElementById(args[arg])
                  if (all){
                        setTimeout(() => {doc.remove(); }, 300);
                        doc.style.opacity = '0'
                  }
                  else{
                        s()
                        function s(){
                               if(doc.firstChild){
                                     doc.firstChild.remove(); s();
                               }
                        }
                  }
            }
      },
//------------------------------------------------------------------------------
      startPage(whatPage){
            start.soManyProblemWithSetTimeout = whatPage
            s()
            function s(){
                  if (app.children.length>0){
                        app.style.transition = 'ease-out 0.5s'
                        app.style.opacity = 0
                        for (let i=0; i<app.children.length; i++){
                              let it = app.children[i]
                              setTimeout(()=>{
                                    it.remove()
                                    s()
                              },500)
                        }
                  }
                  else{
                        let j = start.soManyProblemWithSetTimeout
                        j.start()
                        setTimeout(()=>app.style.opacity = 1,10) //Я НЕ ПОНИМАЮ!!!!!!!!!!!!№;"%:%;%;№;"№!"№!"!"ё!№!№" АААААА
                  }
            }
      },
//------------------------------------------------------------------------------
      renderPageName(namePage){                                                 //div с имянем
            let name = document.createElement('div')
            name.className = 'name'
            name.innerHTML = `<div id='namePage'>${namePage}</div><div id='content'></div>`
            app.append(name)
      },
//------------------------------------------------------------------------------
      getParrentItemTrade(locat,transact){				              //функция для получения массива товаров родителям от детей (потом нужна будет и не тут)
            if(!universe[locat].transact && universe[locat].child){
                 return getParrentItemTrade(universe[locat].child,transact)
            }
            else {return universe[locat][transact]}
      },
//------------------------------------------------------------------------------
      loadObject(src) {                                                         //получения объектов с сервера
            return new Promise(function(resolve, reject) {
                  const xhr = new XMLHttpRequest()
                  xhr.open('GET', src)
                  xhr.responseType = 'json'
                  xhr.onload = ()=>{
                        if(xhr.status >= 400){reject(xhr.response)}
                        else{
                              resolve(this.bufer = xhr.response)
                        }
                  }
                  xhr.onerror = ()=>{reject(xhr.response)}
                  xhr.send()
            });
      },
//------------------------------------------------------------------------------
      loadScript(src) {                                                         //подгрузка скриптов
            return new Promise(function(resolve, reject) {
                  let script = document.createElement('script');
                  script.src = src;
                  script.onload = () => resolve(script);
                  script.onerror = () => reject(new Error(`Ошибка загрузки скрипта ${src}`));
                  document.head.append(script);
            });
      },
//------------------------------------------------------------------------------
      setTableServer(n, url){                                                   //закидываем на серв (доработать)
            let xmlhttp = new XMLHttpRequest();
            xmlhttp.open("POST", url, true);
            xmlhttp.setRequestHeader("Content-Type", "application/json;charset=UTF-8");
            xhr.onreadystatechange = ()=>{if (xhr.readyState === 4 && xhr.status === 200) {console.log(this.responseText)}}
            xmlhttp.send(JSON.stringify(n));
      }
//------------------------------------------------------------------------------
}

document.getElementById(`ie`).remove()

/*        //включу и удалю то, что ниже как только разберусь с сервом

start.loadObject("http://127.0.0.1:3000")
      .then(function() {universe = start.bufer})
      .then(function() {return start.loadObject("http://127.0.0.1:3001")})
      .then(function() {itemTrade = start.bufer})
      .then(function() {return  start.loadScript('js/.js')})
      .then(function() {return  start.loadScript('js/mainPage.js')})
      .then(function() {return  start.loadScript('js/TradeTablePage.js')})
      .then(function() {return  start.loadScript('js/filterPage.js')})

      js\.js
*/


universe = {
	nyx:{
            id: 'nyx',
		name: 'Nyx',
		type: 'System',
		parrent: null,
		child: ['delamar'],
		description: '',
		law: '',
		buy: null,
		sell: null,
		shop: null,
		image: '',
	},
      		delamar:{
                        id: 'delamar',
      			name: 'Delamar',
      			type: 'Planet',
      			parrent: 'nyx',
      			child: ['levski'],
      			description: '',
      			law: '',
      			buy: null,
                        sell: [['Agricultural Supplies',2],['Aluminum',0.11],['Hydrogen',1.9],['Iodine',0.25],['Quartz',1.58],['Waste',0.001]],
                        shop: null,
      			image: '',
      		},
            			levski:{
                                    id: 'levski',
            				name: 'Levski',
            				type: 'Base',
            				parrent: 'delamar',
            				child: null,
            				description: '',
            				law: '',
            				buy: [['Agricultural Supplies',1],['Aluminum',1.11],['Hydrogen',0.9],['Iodine',0.35],['Quartz',1.28],['Waste',0.01]],
            				sell: [['Agricium',27.5],['Astatine',9],['Beryl',4.29],['Chlorine',1.71],['Corundum',2.71],['Diamond',6.77],['Distilled spirits',5.3],['Fluorine',2.91],['Gold',6.41],['Laranite',28.33],['Medical Supplies',17.83],['Processed food',1.5],['Scrap',1.78],['Stims',3.57],['Titanium',8.9],['Tungsten',4.06]],
            				shop: null,
            				image: '',
            			},
      stanton:{
            id: 'stanton',
            name: 'Stanton',
            type: 'System',
            parrent: null,
            child: ['arcCorp','crusader','hurston','microTech'],
            description: '',
            law: '',
            sell: [['Agricultural Supplies',0.5],['Aluminum',1.21],['Hydrogen',0.5],['Iodine',1.35],['Quartz',1.18],['Waste',0.11]],
            buy: null,
            shop: null,
            image: '',
      },
                  arcCorp:{
                        id: 'arcCorp',
                        name: 'ArcCorp',
                        type: 'Planet',
                        parrent: 'stanton',
                        child: ['ARC_L1','area18','baijini_Point','lyria','wala'],
                        description: '',
                        law: '',
                        buy: [['Agricultural Supplies',1.5],['Aluminum',0.21],['Hydrogen',1.5],['Iodine',0.35],['Quartz',1.18],['Waste',0.10]],
                        sell: null,
                        shop: null,
                        image: '',
                  },
                              ARC_L1:{
                                    id: 'ARC_L1',
                                    name: 'ARC-L1',
                                    type: 'asteroidField',
                                    parrent: 'arcCorp',
                                    child: ['R_and_R_ARC_L1'],
                                    description: '',
                                    law: '',
                                    buy: null,
                                    sell: null,
                                    shop: null,
                                    image: '',
                              },
                                          R_and_R_ARC_L1:{
                                                id: 'R_and_R_ARC_L1',
                                                name: 'R&R ARC-L1',
                                                type: 'Station',
                                                parrent: 'ARC_L1',
                                                child: null,
                                                description: '',
                                                law: '',
                                                buy: null,
                                                sell: [['Agricultural Supplies',2],['Aluminum',0.11],['Hydrogen',1.9],['Iodine',0.25],['Quartz',2.28],['Waste',0.001]],
                                                shop: null,
                                                image: '',
                                          },
                              area18:{
                                    id: 'area18',
                                    name: 'Area18',
                                    type: 'Planet',
                                    parrent: 'arcCorp',
                                    child: ['area18_IO_North_Tower','area18_TDD'],
                                    description: '',
                                    law: '',
                                    buy: null,
                                    sell: null,
                                    shop: null,
                                    image: '',
                              },
                                          area18_IO_North_Tower:{
                                                id: 'area18_IO_North_Tower',
                                                name: 'Area18 IO North Tower',
                                                type: 'Base',
                                                parrent: 'area18',
                                                child: null,
                                                description: '',
                                                law: '',
                                                buy: null,
                                                sell: [['Agricultural Supplies',0.5],['Aluminum',2.11],['Hydrogen',0.5],['Iodine',1.35],['Quartz',1.08],['Waste',1.01]],
                                                shop: null,
                                                image: '',
                                          },
                                          area18_TDD:{
                                                id: 'area18_TDD',
                                                name: 'Area18 TDD',
                                                type: 'Base',
                                                parrent: 'area18',
                                                child: null,
                                                description: '',
                                                law: '',
                                                buy: [['Agricultural Supplies',0.5],['Aluminum',2.11],['Hydrogen',0.4],['Iodine',0.85],['Quartz',0.28],['Waste',0.51]],
                                                sell: null,
                                                shop: null,
                                                image: '',
                                          },
                              baijini_Point:{
                                    id: 'baijini_Point',
                                    name: 'Baijini Point',
                                    type: 'Station',
                                    parrent: 'arcCorp',
                                    child: null,
                                    description: '',
                                    law: '',
                                    buy: null,
                                    sell: null,
                                    shop: null,
                                    image: '',
                              },
                              lyria:{
                                    id: 'lyria',
                                    name: 'Lyria',
                                    type: 'Moon',
                                    parrent: 'arcCorp',
                                    child: ['humboldt_Mines','loveridge_Mineral_Reserve','paradise_Cove','shubin_Mining_Facility_SAL_2','shubin_Mining_Facility_SAL_5','the_Orphanage'],
                                    description: '',
                                    law: '',
                                    buy: null,
                                    sell: null,
                                    shop: null,
                                    image: '',
                              },
                                          humboldt_Mines:{
                                                id: 'humboldt_Mines',
                                                name: 'Humboldt Mines',
                                                type: 'Outpost',
                                                parrent: 'lyria',
                                                child: null,
                                                description: '',
                                                law: '',
                                                buy: null,
                                                sell: null,
                                                shop: null,
                                                image: '',
                                          },
                                          loveridge_Mineral_Reserve:{
                                                id: 'loveridge_Mineral_Reserve',
                                                name: 'Loveridge Mineral Reserve',
                                                type: 'Outpost',
                                                parrent: 'lyria',
                                                child: null,
                                                description: '',
                                                law: '',
                                                buy: null,
                                                sell: null,
                                                shop: null,
                                                image: '',
                                          },
                                          paradise_Cove:{
                                                id: 'paradise_Cove',
                                                name: 'Paradise Cove',
                                                type: 'Outpost',
                                                parrent: 'lyria',
                                                child: null,
                                                description: '',
                                                law: '',
                                                buy: null,
                                                sell: null,
                                                shop: null,
                                                image: '',
                                          },
                                          shubin_Mining_Facility_SAL_2:{
                                                id: 'shubin_Mining_Facility_SAL_2',
                                                name: 'Shubin Mining Facility SAL-2',
                                                type: 'Outpost',
                                                parrent: 'lyria',
                                                child: null,
                                                description: '',
                                                law: '',
                                                buy: null,
                                                sell: null,
                                                shop: null,
                                                image: '',
                                          },
                                          shubin_Mining_Facility_SAL_5:{
                                                id: 'shubin_Mining_Facility_SAL_5',
                                                name: 'Shubin Mining Facility SAL-5',
                                                type: 'Outpost',
                                                parrent: 'lyria',
                                                child: null,
                                                description: '',
                                                law: '',
                                                buy: null,
                                                sell: null,
                                                shop: null,
                                                image: '',
                                          },
                                          the_Orphanage:{
                                                id: 'the_Orphanage',
                                                name: 'THe Orphanage',
                                                type: 'Outpost',
                                                parrent: 'lyria',
                                                child: null,
                                                description: '',
                                                law: '',
                                                buy: null,
                                                sell: null,
                                                shop: null,
                                                image: '',
                                          },
                              wala:{
                                    id: 'wala',
                                    name: 'Wala',
                                    type: 'Moon',
                                    parrent: 'arcCorp',
                                    child: ['arcCorp_Mining_Area_045','arcCorp_Mining_Area_048','arcCorp_Mining_Area_056','arcCorp_Mining_Area_061','Samson_and_Sons_Salvage_Center'],
                                    description: '',
                                    law: '',
                                    buy: null,
                                    sell: null,
                                    shop: null,
                                    image: '',
                              },
                                          arcCorp_Mining_Area_045:{
                                                id: 'arcCorp_Mining_Area_045',
                                                name: 'ArcCorp Mining Area 045',
                                                type: 'Outpost',
                                                parrent: 'wala',
                                                child: null,
                                                description: '',
                                                law: '',
                                                buy: null,
                                                sell: null,
                                                shop: null,
                                                image: '',
                                          },
                                          arcCorp_Mining_Area_048:{
                                                id: 'arcCorp_Mining_Area_048',
                                                name: 'ArcCorp Mining Area 048',
                                                type: 'Outpost',
                                                parrent: 'wala',
                                                child: null,
                                                description: '',
                                                law: '',
                                                buy: null,
                                                sell: null,
                                                shop: null,
                                                image: '',
                                          },
                                          arcCorp_Mining_Area_056:{
                                                id: 'arcCorp_Mining_Area_056',
                                                name: 'ArcCorp Mining Area 056',
                                                type: 'Outpost',
                                                parrent: 'wala',
                                                child: null,
                                                description: '',
                                                law: '',
                                                buy: null,
                                                sell: null,
                                                shop: null,
                                                image: '',
                                          },
                                          arcCorp_Mining_Area_061:{
                                                id: 'arcCorp_Mining_Area_061',
                                                name: 'ArcCorp Mining Area 061',
                                                type: 'Outpost',
                                                parrent: 'wala',
                                                child: null,
                                                description: '',
                                                law: '',
                                                buy: null,
                                                sell: null,
                                                shop: null,
                                                image: '',
                                          },
                                          Samson_and_Sons_Salvage_Center:{
                                                id: 'Samson_and_Sons_Salvage_Center',
                                                name: 'Samson & Sons Salvage Center',
                                                type: 'Outpost',
                                                parrent: 'wala',
                                                child: null,
                                                description: '',
                                                law: '',
                                                buy: null,
                                                sell: null,
                                                shop: null,
                                                image: '',
                                          },
                  crusader:{
                        id: 'crusader',
                        name: 'Crusader',
                        type: 'Planet',
                        parrent: 'stanton',
                        child: ['CRU_L1','CRU_L4','CRU_L5','port_Olisar','cellin','daymar','yela'],
                        description: '',
                        law: '',
                        buy: null,
                        sell: null,
                        shop: null,
                        image: '',
                  },
                              CRU_L1:{
                                    id: 'CRU_L1',
                                    name: 'CRU-L1',
                                    type: 'asteroidField',
                                    parrent: 'crusader',
                                    child: ['R_and_R_CRU_L1'],
                                    description: '',
                                    law: '',
                                    buy: null,
                                    sell: null,
                                    shop: null,
                                    image: '',
                              },
                                          R_and_R_CRU_L1:{
                                                id: 'R_and_R_CRU_L1',
                                                name: 'R&R CRU-L1',
                                                type: 'Station',
                                                parrent: 'CRU_L1',
                                                child: null,
                                                description: '',
                                                law: '',
                                                buy: null,
                                                sell: null,
                                                shop: null,
                                                image: '',
                                          },
                              CRU_L4:{
                                    id: 'CRU_L4',
                                    name: 'CRU_L4',
                                    type: 'asteroidField',
                                    parrent: 'crusader',
                                    child: ['R_and_R_CRU_L4','R_and_R_CRU_L4_Hidden_Terminal'],
                                    description: '',
                                    law: '',
                                    buy: null,
                                    sell: null,
                                    shop: null,
                                    image: '',

                              },
                                          R_and_R_CRU_L4:{
                                                id: 'R_and_R_CRU_L4',
                                                name: 'R&R CRU-L4',
                                                type: 'Station',
                                                parrent: 'CRU_L4',
                                                child: null,
                                                description: '',
                                                law: '',
                                                buy: null,
                                                sell: null,
                                                shop: null,
                                                image: '',
                                          },
                                          R_and_R_CRU_L4_Hidden_Terminal:{
                                                id: 'R_and_R_CRU_L4_Hidden_Terminal',
                                                name: 'R&R CRU-L4 Hidden Terminal',
                                                type: 'Station',
                                                parrent: 'CRU_L4',
                                                child: null,
                                                description: '',
                                                law: '',
                                                buy: null,
                                                sell: null,
                                                shop: null,
                                                image: '',
                                          },
                              CRU_L5:{
                                    id: 'CRU_L5',
                                    name: 'CRU-L5',
                                    type: 'asteroidField',
                                    parrent: 'crusader',
                                    child: ['R_and_R_CRU_L5','R_and_R_CRU_L5_Hidden_Terminal'],
                                    description: '',
                                    law: '',
                                    buy: null,
                                    sell: null,
                                    shop: null,
                                    image: '',
                              },
                                          R_and_R_CRU_L5:{
                                                id: 'R_and_R_CRU_L5',
                                                name: 'R&R CRU-L5',
                                                type: 'Station',
                                                parrent: 'CRU_L5',
                                                child: null,
                                                description: '',
                                                law: '',
                                                buy: null,
                                                sell: null,
                                                shop: null,
                                                image: '',
                                          },
                                          R_and_R_CRU_L5_Hidden_Terminal:{
                                                id: 'R_and_R_CRU_L5_Hidden_Terminal',
                                                name: 'R&R CRU-L5 Hidden Terminal',
                                                type: 'Station',
                                                parrent: 'CRU_L5',
                                                child: null,
                                                description: '',
                                                law: '',
                                                buy: null,
                                                sell: null,
                                                shop: null,
                                                image: '',
                                          },
                              port_Olisar:{
                                    id: 'port_Olisar',
                                    name: 'Port Olisar',
                                    type: 'Station',
                                    parrent: 'crusader',
                                    child: null,
                                    description: '',
                                    law: '',
                                    buy: null,
                                    sell: null,
                                    shop: null,
                                    image: '',
                              },
                              cellin:{
                                    id: 'cellin',
                                    name: 'Cellin',
                                    type: 'Moon',
                                    parrent: 'crusader',
                                    child: ['gallete_Family_Farms','hickes_Research','private_Property','terra_Mills_HydroFarm','tram_and_Myers_Mining'],
                                    description: '',
                                    law: '',
                                    buy: null,
                                    sell: null,
                                    shop: null,
                                    image: '',
                              },
                                          gallete_Family_Farms:{
                                                id: 'gallete_Family_Farms',
                                                name: 'Gallete Family Farms',
                                                type: 'Outpost',
                                                parrent: 'cellin',
                                                child: null,
                                                description: '',
                                                law: '',
                                                buy: null,
                                                sell: null,
                                                shop: null,
                                                image: '',
                                          },
                                          hickes_Research:{
                                                id: 'hickes_Research',
                                                name: 'Hickes Research',
                                                type: 'Outpost',
                                                parrent: 'cellin',
                                                child: null,
                                                description: '',
                                                law: '',
                                                buy: null,
                                                sell: null,
                                                shop: null,
                                                image: '',
                                          },
                                          private_Property:{
                                                id: 'private_Property',
                                                name: 'Private Property',
                                                type: 'Outpost',
                                                parrent: 'cellin',
                                                child: null,
                                                description: '',
                                                law: '',
                                                buy: null,
                                                sell: null,
                                                shop: null,
                                                image: '',
                                          },
                                          terra_Mills_HydroFarm:{
                                                id: 'terra_Mills_HydroFarm',
                                                name: 'Terra Mills HydroFarm',
                                                type: 'Outpost',
                                                parrent: 'cellin',
                                                child: null,
                                                description: '',
                                                law: '',
                                                buy: null,
                                                sell: null,
                                                shop: null,
                                                image: '',
                                          },
                                          tram_and_Myers_Mining:{
                                                id: 'tram_and_Myers_Mining',
                                                name: 'Tram & Myers Mining',
                                                type: 'Outpost',
                                                parrent: 'cellin',
                                                child: null,
                                                description: '',
                                                law: '',
                                                buy: null,
                                                sell: null,
                                                shop: null,
                                                image: '',
                                          },
                              daymar:{
                                    id: 'daymar',
                                    name: 'Daymar',
                                    type: 'Moon',
                                    parrent: 'crusader',
                                    child: ['arcCorp_Mining_141','bountiful_Harvest_Hydroponics','brios_Breaker_Yard','kudre_Ore','nuen_Waste_Management','shubin_Mining_Facility_SCD_1'],
                                    description: '',
                                    law: '',
                                    buy: null,
                                    sell: null,
                                    shop: null,
                                    image: '',
                              },
                                          arcCorp_Mining_141:{
                                                id: 'arcCorp_Mining_141',
                                                name: 'ArcCorp Mining 141',
                                                type: 'Outpost',
                                                parrent: 'daymar',
                                                child: null,
                                                description: '',
                                                law: '',
                                                buy: null,
                                                sell: null,
                                                shop: null,
                                                image: '',
                                          },
                                          bountiful_Harvest_Hydroponics:{
                                                id: 'bountiful_Harvest_Hydroponics',
                                                name: 'Bountiful Harvest Hydroponics',
                                                type: 'Outpost',
                                                parrent: 'daymar',
                                                child: null,
                                                description: '',
                                                law: '',
                                                buy: null,
                                                sell: null,
                                                shop: null,
                                                image: '',
                                          },
                                          brios_Breaker_Yard:{
                                                id: 'brios_Breaker_Yard',
                                                name: 'Brios Breaker Yard',
                                                type: 'Outpost',
                                                parrent: 'daymar',
                                                child: null,
                                                description: '',
                                                law: '',
                                                buy: null,
                                                sell: null,
                                                shop: null,
                                                image: '',
                                          },
                                          kudre_Ore:{
                                                id: 'kudre_Ore',
                                                name: 'Kudre Ore',
                                                type: 'Outpost',
                                                parrent: 'daymar',
                                                child: null,
                                                description: '',
                                                law: '',
                                                buy: null,
                                                sell: null,
                                                shop: null,
                                                image: '',
                                          },
                                          nuen_Waste_Management:{
                                                id: 'nuen_Waste_Management',
                                                name: 'Nuen Waste Management',
                                                type: 'Outpost',
                                                parrent: 'daymar',
                                                child: null,
                                                description: '',
                                                law: '',
                                                buy: null,
                                                sell: null,
                                                shop: null,
                                                image: '',
                                          },
                                          shubin_Mining_Facility_SCD_1:{
                                                id: 'shubin_Mining_Facility_SCD_1',
                                                name: 'Shubin Mining Facility SCD-1',
                                                type: 'Outpost',
                                                parrent: 'daymar',
                                                child: null,
                                                description: '',
                                                law: '',
                                                buy: null,
                                                sell: null,
                                                shop: null,
                                                image: '',
                                          },
                              yela:{
                                    id: 'yela',
                                    name: 'Yela',
                                    type: 'Moon',
                                    parrent: 'crusader',
                                    child: ['arcCorp_Mining_157','benson_Mining_Outpost','deakins_Research','grimHEX','jumptown','NT_999_XX'],
                                    description: '',
                                    law: '',
                                    buy: null,
                                    sell: null,
                                    shop: null,
                                    image: '',
                              },
                                          arcCorp_Mining_157:{
                                                id: 'arcCorp_Mining_157',
                                                name: 'ArcCorp Mining 157',
                                                type: 'Outpost',
                                                parrent: 'yela',
                                                child: null,
                                                description: '',
                                                law: '',
                                                buy: null,
                                                sell: null,
                                                shop: null,
                                                image: '',
                                          },
                                          benson_Mining_Outpost:{
                                                id: 'benson_Mining_Outpost',
                                                name: 'Benson Mining Outpost',
                                                type: 'Outpost',
                                                parrent: 'yela',
                                                child: null,
                                                description: '',
                                                law: '',
                                                buy: null,
                                                sell: null,
                                                shop: null,
                                                image: '',
                                          },
                                          deakins_Research:{
                                                id: 'deakins_Research',
                                                name: 'Deakins Research',
                                                type: 'Outpost',
                                                parrent: 'yela',
                                                child: null,
                                                description: '',
                                                law: '',
                                                buy: null,
                                                sell: null,
                                                shop: null,
                                                image: '',
                                          },
                                          grimHEX:{
                                                id: 'grimHEX',
                                                name: 'GrimHEX',
                                                type: 'Station',
                                                parrent: 'yela',
                                                child: null,
                                                description: '',
                                                law: '',
                                                buy: null,
                                                sell: null,
                                                shop: null,
                                                image: '',
                                          },
                                          jumptown:{
                                                id: 'jumptown',
                                                name: 'Jumptown',
                                                type: 'Outpost',
                                                parrent: 'yela',
                                                child: null,
                                                description: '',
                                                law: '',
                                                buy: null,
                                                sell: null,
                                                shop: null,
                                                image: '',
                                          },
                                          NT_999_XX:{
                                                id: 'NT_999_XX',
                                                name: 'NT_999_XX',
                                                type: 'Outpost',
                                                parrent: 'yela',
                                                child: null,
                                                description: '',
                                                law: '',
                                                buy: null,
                                                sell: null,
                                                shop: null,
                                                image: '',
                                          },
                  hurston:{
                        id: 'hurston',
                        name: 'Hurston',
                        type: 'Planet',
                        parrent: 'stanton',
                        child: ['everus_Harbor','HDMS_Edmond','HDMS_Hadley','HDMS_Oparei','HDMS_Pinewood','HDMS_Stanhope','HDMS_Thedus','HUR_L1','HUR_L2','HUR_L3','HUR_L4','HUR_L5','lorville','aberdeen','arial','ita','magda','reclamation_and_Disposal_Orinth'],
                        description: '',
                        law: '',
                        buy: null,
                        sell: null,
                        shop: null,
                        image: '',
                  },
                              everus_Harbor:{
                                    id: 'everus_Harbor',
                                    name: 'Everus Harbor',
                                    type: 'Station',
                                    parrent: 'hurston',
                                    child: null,
                                    description: '',
                                    law: '',
                                    buy: null,
                                    sell: null,
                                    shop: null,
                                    image: '',
                              },
                              HDMS_Edmond:{
                                    id: 'HDMS_Edmond',
                                    name: 'HDMS Edmond',
                                    type: 'Outpost',
                                    parrent: 'hurston',
                                    child: null,
                                    description: '',
                                    law: '',
                                    buy: null,
                                    sell: null,
                                    shop: null,
                                    image: '',
                              },
                              HDMS_Hadley:{
                                    id: 'HDMS_Hadley',
                                    name: 'HDMS Hadley',
                                    type: 'Outpost',
                                    parrent: 'hurston',
                                    child: null,
                                    description: '',
                                    law: '',
                                    buy: null,
                                    sell: null,
                                    shop: null,
                                    image: '',
                              },
                              HDMS_Oparei:{
                                    id: 'HDMS_Oparei',
                                    name: 'HDMS Oparei',
                                    type: 'Outpost',
                                    parrent: 'hurston',
                                    child: null,
                                    description: '',
                                    law: '',
                                    buy: null,
                                    sell: null,
                                    shop: null,
                                    image: '',
                              },
                              HDMS_Pinewood:{
                                    id: 'HDMS_Pinewood',
                                    name: 'HDMS Pinewood',
                                    type: 'Outpost',
                                    parrent: 'hurston',
                                    child: null,
                                    description: '',
                                    law: '',
                                    buy: null,
                                    sell: null,
                                    shop: null,
                                    image: '',
                              },
                              HDMS_Stanhope:{
                                    id: 'HDMS_Stanhope',
                                    name: 'HDMS Stanhope',
                                    type: 'Outpost',
                                    parrent: 'hurston',
                                    child: null,
                                    description: '',
                                    law: '',
                                    buy: null,
                                    sell: null,
                                    shop: null,
                                    image: '',
                              },
                              HDMS_Thedus:{
                                    id: 'HDMS_Thedus',
                                    name: 'HDMS Thedus',
                                    type: 'Outpost',
                                    parrent: 'hurston',
                                    child: null,
                                    description: '',
                                    law: '',
                                    buy: null,
                                    sell: null,
                                    shop: null,
                                    image: '',
                              },
                              HUR_L1:{
                                    id: 'HUR_L1',
                                    name: 'HUR-L1',
                                    type: 'asteroidField',
                                    parrent: 'hurston',
                                    child: ['R_and_R_HUR_L1'],
                                    description: '',
                                    law: '',
                                    buy: null,
                                    sell: null,
                                    shop: null,
                                    image: '',
                              },
                                          R_and_R_HUR_L1:{
                                                id: 'R_and_R_HUR_L1',
                                                name: 'R&R HUR-L1',
                                                type: 'Station',
                                                parrent: 'HUR_L1',
                                                child: null,
                                                description: '',
                                                law: '',
                                                buy: null,
                                                sell: null,
                                                shop: null,
                                                image: '',
                                          },
                              HUR_L2:{
                                    id: 'HUR_L2',
                                    name: 'HUR-L2',
                                    type: 'asteroidField',
                                    parrent: 'hurston',
                                    child: ['R_and_R_HUR_L2'],
                                    description: '',
                                    law: '',
                                    buy: null,
                                    sell: null,
                                    shop: null,
                                    image: '',
                              },
                                          R_and_R_HUR_L2:{
                                                id: 'R_and_R_HUR_L2',
                                                name: 'R&R HUR-L2',
                                                type: 'Station',
                                                parrent: 'HUR_L2',
                                                child: null,
                                                description: '',
                                                law: '',
                                                buy: null,
                                                sell: null,
                                                shop: null,
                                                image: '',
                                          },
                              HUR_L3:{
                                    id: 'HUR_L3',
                                    name: 'HUR-L3',
                                    type: 'asteroidField',
                                    parrent: 'hurston',
                                    child: ['R_and_R_HUR_L3'],
                                    description: '',
                                    law: '',
                                    buy: null,
                                    sell: null,
                                    shop: null,
                                    image: '',
                              },
                                          R_and_R_HUR_L3:{
                                                id: 'R_and_R_HUR_L3',
                                                name: 'R&R HUR-L3',
                                                type: 'Station',
                                                parrent: 'HUR_L3',
                                                child: null,
                                                description: '',
                                                law: '',
                                                buy: null,
                                                sell: null,
                                                shop: null,
                                                image: '',
                                          },
                              HUR_L4:{
                                    id: 'HUR_L4',
                                    name: 'HUR-L4',
                                    type: 'asteroidField',
                                    parrent: 'hurston',
                                    child: ['R_and_R_HUR_L4'],
                                    description: '',
                                    law: '',
                                    buy: null,
                                    sell: null,
                                    shop: null,
                                    image: '',
                              },
                                          R_and_R_HUR_L4:{
                                                id: 'R_and_R_HUR_L4',
                                                name: 'R&R HUR-L4',
                                                type: 'Station',
                                                parrent: 'HUR_L4',
                                                child: null,
                                                description: '',
                                                law: '',
                                                buy: null,
                                                sell: null,
                                                shop: null,
                                                image: '',
                                          },
                              HUR_L5:{
                                    id: 'HUR_L5',
                                    name: 'HUR-L5',
                                    type: 'asteroidField',
                                    parrent: 'hurston',
                                    child: ['R_and_R_HUR_L5'],
                                    description: '',
                                    law: '',
                                    buy: null,
                                    sell: null,
                                    shop: null,
                                    image: '',
                              },
                                          R_and_R_HUR_L5:{
                                                id: 'R_and_R_HUR_L5',
                                                name: 'R&R HUR-L5',
                                                type: 'Station',
                                                parrent: 'HUR_L5',
                                                child: null,
                                                description: '',
                                                law: '',
                                                buy: null,
                                                sell: null,
                                                shop: null,
                                                image: '',
                                          },
                              lorville:{
                                    id: 'lorville',
                                    name: 'Lorville',
                                    type: 'Base',
                                    parrent: 'hurston',
                                    child: ['lorville_CBD','lorville_L19_Admin_Office'],
                                    description: '',
                                    law: '',
                                    buy: null,
                                    sell: null,
                                    shop: null,
                                    image: '',
                              },
                                          lorville_CBD:{
                                                id: 'lorville_CBD',
                                                name: 'Lorville-CBD',
                                                type: 'Base',
                                                parrent: 'lorville',
                                                child: null,
                                                description: '',
                                                law: '',
                                                buy: null,
                                                sell: null,
                                                shop: null,
                                                image: '',
                                          },
                                          lorville_L19_Admin_Office:{
                                                id: 'lorville_L19_Admin_Office',
                                                name: 'Lorville L19 Admin Office',
                                                type: 'Base',
                                                parrent: 'lorville',
                                                child: null,
                                                description: '',
                                                law: '',
                                                buy: null,
                                                sell: null,
                                                shop: null,
                                                image: '',
                                          },
                              aberdeen:{
                                    id: 'aberdeen',
                                    name: 'Aberdeen',
                                    type: 'Moon',
                                    parrent: 'hurston',
                                    child: ['HDMS_Anderson','HDMS_Norgaard'],
                                    description: '',
                                    law: '',
                                    buy: null,
                                    sell: null,
                                    shop: null,
                                    image: '',
                              },
                                          HDMS_Anderson:{
                                                id: 'HDMS_Anderson',
                                                name: 'HDMS Anderson',
                                                type: 'Outpost',
                                                parrent: 'aberdeen',
                                                child: null,
                                                description: '',
                                                law: '',
                                                buy: null,
                                                sell: null,
                                                shop: null,
                                                image: '',
                                          },
                                          HDMS_Norgaard:{
                                                id: 'HDMS_Norgaard',
                                                name: 'HDMS Norgaard',
                                                type: 'Outpost',
                                                parrent: 'aberdeen',
                                                child: null,
                                                description: '',
                                                law: '',
                                                buy: null,
                                                sell: null,
                                                shop: null,
                                                image: '',
                                          },
                              arial:{
                                    id: 'arial',
                                    name: 'Arial',
                                    type: 'Moon',
                                    parrent: 'hurston',
                                    child: ['HDMS_Bezdek','HDMS_Lathan'],
                                    description: '',
                                    law: '',
                                    buy: null,
                                    sell: null,
                                    shop: null,
                                    image: '',
                              },
                                          HDMS_Bezdek:{
                                                id: 'HDMS_Bezdek',
                                                name: 'HDMS Bezdek',
                                                type: 'Outpost',
                                                parrent: 'arial',
                                                child: null,
                                                description: '',
                                                law: '',
                                                buy: null,
                                                sell: null,
                                                shop: null,
                                                image: '',
                                          },
                                          HDMS_Lathan:{
                                                id: 'HDMS_Lathan',
                                                name: 'HDMS Lathan',
                                                type: 'Outpost',
                                                parrent: 'arial',
                                                child: null,
                                                description: '',
                                                law: '',
                                                buy: null,
                                                sell: null,
                                                shop: null,
                                                image: '',
                                          },
                              ita:{
                                    id: 'ita',
                                    name: 'Ita',
                                    type: 'Moon',
                                    parrent: 'hurston',
                                    child: ['HDMS_Ryder','HDMS_Woodruff'],
                                    description: '',
                                    law: '',
                                    buy: null,
                                    sell: null,
                                    shop: null,
                                    image: '',
                              },
                                          HDMS_Ryder:{
                                                id: 'HDMS_Ryder',
                                                name: 'HDMS Ryder',
                                                type: 'Outpost',
                                                parrent: 'ita',
                                                child: null,
                                                description: '',
                                                law: '',
                                                buy: null,
                                                sell: null,
                                                shop: null,
                                                image: '',
                                          },
                                          HDMS_Woodruff:{
                                                id: 'HDMS_Woodruff',
                                                name: 'HDMS Woodruff',
                                                type: 'Outpost',
                                                parrent: 'ita',
                                                child: null,
                                                description: '',
                                                law: '',
                                                buy: null,
                                                sell: null,
                                                shop: null,
                                                image: '',
                                          },
                              magda:{
                                    id: 'magda',
                                    name: 'Magda',
                                    type: 'Moon',
                                    parrent: 'hurston',
                                    child: ['HDMS_Hahn','HDMS_Perlman'],
                                    description: '',
                                    law: '',
                                    buy: null,
                                    sell: null,
                                    shop: null,
                                    image: '',
                              },
                                          HDMS_Hahn:{
                                                id: 'HDMS_Hahn',
                                                name: 'HDMS Hahn',
                                                type: 'Outpost',
                                                parrent: 'magda',
                                                child: null,
                                                description: '',
                                                law: '',
                                                buy: null,
                                                sell: null,
                                                shop: null,
                                                image: '',
                                          },
                                          HDMS_Perlman:{
                                                id: 'HDMS_Perlman',
                                                name: 'HDMS Perlman',
                                                type: 'Outpost',
                                                parrent: 'magda',
                                                child: null,
                                                description: '',
                                                law: '',
                                                buy: null,
                                                sell: null,
                                                shop: null,
                                                image: '',
                                          },
                              reclamation_and_Disposal_Orinth:{
                                    id: 'reclamation_and_Disposal_Orinth',
                                    name: 'Reclamation & Disposal Orinth',
                                    type: 'Outpost',
                                    parrent: 'hurston',
                                    child: null,
                                    description: '',
                                    law: '',
                                    buy: null,
                                    sell: null,
                                    shop: null,
                                    image: '',
                                          },
                  microTech:{
                        id: 'microTech',
                        name: 'microTech',
                        type: 'Planet',
                        parrent: 'stanton',
                        child: ['MIC_L1','new_Babbage','outpost_54','port_Tressler','rayari_Deltana_Research_Outpost','shubin_Mining_Facility_SM0_10','shubin_Mining_Facility_SM0_13','shubin_Mining_Facility_SM0_18','shubin_Mining_Facility_SM0_22','calliope','clio','euterpe'],
                        description: '',
                        law: '',
                        buy: null,
                        sell: null,
                        shop: null,
                        image: '',
                  },
                              MIC_L1:{
                                    id: 'MIC_L1',
                                    name: 'MIC-L1',
                                    type: 'asteroidField',
                                    parrent: 'microTech',
                                    child: ['R_and_R_MIC_L1'],
                                    description: '',
                                    law: '',
                                    buy: null,
                                    sell: null,
                                    shop: null,
                                    image: '',
                              },
                                          R_and_R_MIC_L1:{
                                                id: 'R_and_R_MIC_L1',
                                                name: 'R&R MIC-L1',
                                                type: 'Station',
                                                parrent: 'MIC_L1',
                                                child: null,
                                                description: '',
                                                law: '',
                                                buy: null,
                                                sell: null,
                                                shop: null,
                                                image: '',
                                          },
                              new_Babbage:{
                                    id: 'new_Babbage',
                                    name: 'New Babbage',
                                    type: 'Base',
                                    parrent: 'microTech',
                                    child: ['new_Babbage_MT_Planetary_Services','new_Babbage_TDD'],
                                    description: '',
                                    law: '',
                                    buy: null,
                                    sell: null,
                                    shop: null,
                                    image: '',
                              },
                                          new_Babbage_MT_Planetary_Services:{
                                                id: 'new_Babbage_MT_Planetary_Services',
                                                name: 'New Babbage MT Planetary Services',
                                                type: 'Base',
                                                parrent: 'microTech',
                                                child: null,
                                                description: '',
                                                law: '',
                                                buy: null,
                                                sell: null,
                                                shop: null,
                                                image: '',
                                          },
                                          new_Babbage_TDD:{
                                                id: 'new_Babbage_TDD',
                                                name: 'New Babbage TDD',
                                                type: 'Base',
                                                parrent: 'microTech',
                                                child: null,
                                                description: '',
                                                law: '',
                                                buy: null,
                                                sell: null,
                                                shop: null,
                                                image: '',
                                          },
                              outpost_54:{
                                    id: 'outpost_54',
                                    name: 'Outpost 54',
                                    type: 'Outpost',
                                    parrent: 'microTech',
                                    child: null,
                                    description: '',
                                    law: '',
                                    buy: null,
                                    sell: null,
                                    shop: null,
                                    image: '',
                              },
                              port_Tressler:{
                                    id: 'port_Tressler',
                                    name: 'Port Tressler',
                                    type: 'Station',
                                    parrent: 'microTech',
                                    child: null,
                                    description: '',
                                    law: '',
                                    buy: null,
                                    sell: null,
                                    shop: null,
                                    image: '',
                              },
                              rayari_Deltana_Research_Outpost:{
                                    id: 'rayari_Deltana_Research_Outpost',
                                    name: 'Rayari Deltana Research Outpost',
                                    type: 'Outpost',
                                    parrent: 'microTech',
                                    child: null,
                                    description: '',
                                    law: '',
                                    buy: null,
                                    sell: null,
                                    shop: null,
                                    image: '',
                              },
                              shubin_Mining_Facility_SM0_10:{
                                    id: 'shubin_Mining_Facility_SM0_10',
                                    name: 'Shubin Mining Facility SM0-10',
                                    type: 'Outpost',
                                    parrent: 'microTech',
                                    child: null,
                                    description: '',
                                    law: '',
                                    buy: null,
                                    sell: null,
                                    shop: null,
                                    image: '',
                              },
                              shubin_Mining_Facility_SM0_13:{
                                    id: 'shubin_Mining_Facility_SM0_13',
                                    name: 'Shubin Mining Facility SM0-13',
                                    type: 'Outpost',
                                    parrent: 'microTech',
                                    child: null,
                                    description: '',
                                    law: '',
                                    buy: null,
                                    sell: null,
                                    shop: null,
                                    image: '',
                              },
                              shubin_Mining_Facility_SM0_18:{
                                    id: 'shubin_Mining_Facility_SM0_18',
                                    name: 'Shubin Mining Facility SM0-18',
                                    type: 'Outpost',
                                    parrent: 'microTech',
                                    child: null,
                                    description: '',
                                    law: '',
                                    buy: null,
                                    sell: null,
                                    shop: null,
                                    image: '',
                              },
                              shubin_Mining_Facility_SM0_22:{
                                    id: 'shubin_Mining_Facility_SM0_22',
                                    name: 'Shubin Mining Facility SM0-22',
                                    type: 'Outpost',
                                    parrent: 'microTech',
                                    child: null,
                                    description: '',
                                    law: '',
                                    buy: null,
                                    sell: null,
                                    shop: null,
                                    image: '',
                              },
                              calliope:{
                                    id: 'calliope',
                                    name: 'Calliope',
                                    type: 'Moon',
                                    parrent: 'microTech',
                                    child: ['ravens_Roost','rayari_Anvik_Research_Outpost','rayari_Kaltag_Research_Outpost','shubin_Mining_Facility_SMCa_6','shubin_Mining_Facility_SMCa_8'],
                                    description: '',
                                    law: '',
                                    buy: null,
                                    sell: null,
                                    shop: null,
                                    image: '',
                              },
                                          ravens_Roost:{
                                                id: 'ravens_Roost',
                                                name: 'Ravens Roost',
                                                type: 'Outpost',
                                                parrent: 'microTech',
                                                child: null,
                                                description: '',
                                                law: '',
                                                buy: null,
                                                sell: null,
                                                shop: null,
                                                image: '',
                                          },
                                          rayari_Anvik_Research_Outpost:{
                                                id: 'rayari_Anvik_Research_Outpost',
                                                name: 'Rayari Anvik Research Outpost',
                                                type: 'Outpost',
                                                parrent: 'microTech',
                                                child: null,
                                                description: '',
                                                law: '',
                                                buy: null,
                                                sell: null,
                                                shop: null,
                                                image: '',
                                          },
                                          rayari_Kaltag_Research_Outpost:{
                                                id: 'rayari_Kaltag_Research_Outpost',
                                                name: 'Rayari Kaltag Research Outpost',
                                                type: 'Outpost',
                                                parrent: 'microTech',
                                                child: null,
                                                description: '',
                                                law: '',
                                                buy: null,
                                                sell: null,
                                                shop: null,
                                                image: '',
                                          },
                                          shubin_Mining_Facility_SMCa_6:{
                                                id: 'shubin_Mining_Facility_SMCa_6',
                                                name: 'Shubin Mining Facility SMCa-6',
                                                type: 'Outpost',
                                                parrent: 'microTech',
                                                child: null,
                                                description: '',
                                                law: '',
                                                buy: null,
                                                sell: null,
                                                shop: null,
                                                image: '',
                                          },
                                          shubin_Mining_Facility_SMCa_8:{
                                                id: 'shubin_Mining_Facility_SMCa_8',
                                                name: 'Shubin Mining Facility SMCa-8',
                                                type: 'Outpost',
                                                parrent: 'microTech',
                                                child: null,
                                                description: '',
                                                law: '',
                                                buy: null,
                                                sell: null,
                                                shop: null,
                                                image: '',
                                          },
                              clio:{
                                    id: 'clio',
                                    name: 'Clio',
                                    type: 'Moon',
                                    parrent: 'microTech',
                                    child: ['rayari_Cantwell_Research_Outpost','rayari_McGrath_Research_Outpost'],
                                    description: '',
                                    law: '',
                                    buy: null,
                                    sell: null,
                                    shop: null,
                                    image: '',
                              },
                                          rayari_Cantwell_Research_Outpost:{
                                                id: 'rayari_Cantwell_Research_Outpost',
                                                name: 'Rayari Cantwell Research Outpost',
                                                type: 'Moon',
                                                parrent: 'microTech',
                                                child: null,
                                                description: '',
                                                law: '',
                                                buy: null,
                                                sell: null,
                                                shop: null,
                                                image: '',
                                          },
                                          rayari_McGrath_Research_Outpost:{
                                                id: 'rayari_McGrath_Research_Outpost',
                                                name: 'Rayari McGrath Research Outpost',
                                                type: 'Moon',
                                                parrent: 'microTech',
                                                child: null,
                                                description: '',
                                                law: '',
                                                buy: null,
                                                sell: null,
                                                shop: null,
                                                image: '',
                                          },
                              euterpe:{
                                    id: 'euterpe',
                                    name: 'Euterpe',
                                    type: 'Moon',
                                    parrent: 'microTech',
                                    child: ['buds_Growery'],
                                    description: '',
                                    law: '',
                                    buy: null,
                                    sell: null,
                                    shop: null,
                                    image: '',
                              },
                                          buds_Growery:{
                                                id: 'buds_Growery',
                                                name: 'Buds Growery',
                                                type: 'Moon',
                                                parrent: 'euterpe',
                                                child: null,
                                                description: '',
                                                law: '',
                                                buy: null,
                                                sell: null,
                                                shop: null,
                                                image: '',
                                          },
}                                                                  //удалить как только разберусь с сервом
itemTrade = {
	agricium:{
            id: 'agricium',
		name: 'Agricium',
		description: '',
		image: '',
	},
	agricultural_supplies:{
            id: 'agricultural_supplies',
		name: 'Agricultural Supplies',
		description: '',
		image: '',
	},
	altruciatoxin:{
            id: 'altruciatoxin',
		name: 'altruciatoxin',
		description: '',
		image: '',
	},
	aluminum:{
            id: 'aluminum',
		name: 'Aluminum',
		description: '',
		image: '',
	},
	astatine:{
            id: 'astatine',
		name: 'Astatine',
		description: '',
		image: '',
	},
	beryl:{
            id: 'beryl',
		name: 'Beryl',
		description: '',
		image: '',
	},
	chlorine:{
            id: 'chlorine',
		name: 'Chlorine',
		description: '',
		image: '',
	},
	corundum:{
            id: 'corundum',
		name: 'Corundum',
		description: '',
		image: '',
	},
	diamond:{
            id: 'diamond',
		name: 'Diamond',
		description: '',
		image: '',
	},
	distilled_spirits:{
            id: 'distilled_spirits',
		name: 'Distilled spirits',
		description: '',
		image: '',
	},
	etam:{
            id: 'etam',
		name: 'Etam',
		description: '',
		image: '',
	},
	fluorine:{
            id: 'fluorine',
		name: "Fluorine",
		description: '',
		image: '',
	},
	gold:{
            id: 'gold',
		name: "Gold",
		description: '',
		image: '',
	},
	hydrogen:{
            id: 'hydrogen',
		name: "Hydrogen",
		description: '',
		image: '',
	},
	iodine:{
            id: 'iodine',
		name: "Iodine",
		description: '',
		image: '',
	},
	laranite:{
            id: 'laranite',
		name: "Laranite",
		description: '',
		image: '',
	},
	maze:{
            id: 'maze',
		name: "Maze",
		description: '',
		image: '',
	},
	medical_supplies:{
            id: 'medical_supplies',
		name: "Medical Supplies",
		description: '',
		image: '',
	},
	neon:{
            id: 'neon',
		name: "Neon",
		description: '',
		image: '',
	},
	processed_food:{
            id: 'processed_food',
		name: "Processed food",
		description: '',
		image: '',
	},
	quartz:{
            id: 'quartz',
		name: "Quartz",
		description: '',
		image: '',
	},
	revenant_tree_pollen:{
            id: 'revenant_tree_pollen',
		name: "Revenant Tree Pollen",
		description: '',
		image: '',
	},
	scrap:{
            id: 'scrap',
		name: "Scrap",
		description: '',
		image: '',
	},
	slam:{
            id: 'slam',
		name: "SLAM",
		description: '',
		image: '',
	},
	stims:{
            id: 'stims',
		name: "Stims",
		description: '',
		image: '',
	},
	titanium:{
            id: 'titanium',
		name: "Stims",
		description: '',
		image: '',
	},
	tungsten:{
            id: 'tungsten',
		name: "Tungsten",
		description: '',
		image: '',
	},
	waste:{
            id: 'waste',
		name: "Waste",
		description: '',
		image: '',
	},
	widow:{
            id: 'widow',
		name: "WiDoW",
		description: '',
		image: '',
	},
}                                                                 //удалить как только разберусь с сервом
start.loadScript('js/TradeTablePage.js')                                            //удалить как только разберусь с сервом
start.loadScript('js/filterPage.js')                                            //удалить как только разберусь с сервом
start.loadScript('js/mainPage.js')                                              //удалить как только разберусь с сервом
start.loadScript('js/startPage.js')                                             //удалить как только разберусь с сервом
